name: bicep-deployment
on:
    push:
        branches:
            - main
            pull_request:
                branches:
                    - main
    workflow_dispatch:

    env:
        RESOURCE_GROUP: WinRG
        ENVIRONMENT: test
name: MyWorkflow

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: repo
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template-file: ./main.bicep
        parameters: environmentType=${{ github.event.inputs.environment || 'dev' }}
        failOnStdErr: false