name: deploy-toy-website
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    workflow_dispatch:

env: 
  RESOURCE_GROUP: rg-bicep-github-actions-037
  ENVIROMENT    : test


jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checking out respository'
              uses: actions/checkout@v2
              with:
                  path: repo
            - name: 'logging in to azure'
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            -name: 'Create a Resource Group'
             uses: Azure/cli@v1.0.6
             with:
                inlineScript: |
                  az version
                  az group create -n $RESOURCE_GROUP -1 eastus
            - name: 'Deploying to azure'
              uses: azure/arm-deploy@v1
              with:
                  resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
                  template: ./deploy/main.bicep
                  parameters: enviromentType=${{ env.ENVIROMENT }}
            